orbs:
  apex: circleci/salesforce-apex@x.y
version: 2.1
workflows:
  deploy_test:
    jobs:
      - apex/scratch-deploy-and-test:
          defaultusername: circleci
          deploydir: ./src
          permset: circleci
          sampledata-path: ./sampledata
          scratch-alias: circleci
          scratch-def: ./config/project-scratch-def.json
